truths = [
    "Onko sinulla ihastusta?",
    "Mikä on pahin tapasi?",
    "Onko sinulla salaista ihastusta?",
    "Oletko koskaan valedellut, miksi olet myöhässä koulusta?",
    "Mikä on pahin ateria, mitä äitisi tai isäsi on keittiössä valmistanut?",
    "Haluaisitko mielummin lemmikin vai sisaruksen?",
    "Oletko koskaan pissannut sänkyyn tai uima-altaaseen?",
    "Kuka julkkis haluaisit olla ja miksi?",
    "Oletko koskaan itkenyt elokuvan aikana?",
    "Luistatko koskaan kotitöistä, ja jos luistat, mikä on tekosyysi?",
    "Oletko koskaan lintsannut?",
    "Mikä haluat olla isona?",
    "Pelkäätkö pimeää?",
    "Mikä on pelottavin näkemäsi painajainen?",
    "Minkä yhden asian muuttaisit itsessäsi?",
    "Jos tapaisit lampunhengen, mitkä olisivat toivomasi kolme asiaa?",
    "Haluaisitko vaihtaa oman nimesi?",
    "Haluaisitko mennä rannalle tai vuorille nyt?",
    "Mikä on lempiruokasi?",
    "Pidätkö romanttisista elokuvista?",
    "Mikä supersankari on huonoin kaikista?",
    "Mikä on lempinimesi?",
    "Mikä on vähiten suosikki lahja, jonka olet koskaan saanut?",
    "Mitä tekisit, jos olisit jättiläinen?",
    "Pidätkö hot dogeista?",
    "Onko sinut kutsuttu snitchiksi?",
    "Oletko koskaan avannut joululahjoja ennen jouluaattoa?",
    "Mikä on suosikki urheilulajisi?",
    "Jos sinulla olisi aikakone, minne haluaisit mennä?",
    "Mikä on ensimmäinen asia, jonka teet koulun jälkeen?",
    "Onko sänkysi alla piilossa jotain?",
    "Minkä mieluummin syöt ruuaksi: pikaruokaa vai äidin kotiruokaa?",
    "Milloin viimeksi pyysit anteeksi?",
    "Mitä pidät eniten kaikista huoneessasi olevista asioista?",
    "Kuka on suosikki elokuva hahmosi?",
    "Puretko/syötkö kynsiäsi?"
]

dares = [
    "Lyö itseäsi 5 kertaa. (älä kovaa)",
    "Älä räpytä silmiäsi minuuttiin.",
    "Mene ulos ja huuda 'Kaivan nenää' ensimmäiselle ihmiselle, johon törmäät.",
    "Aseta jalkasi pääsi taakse.",
    "Mene ulos ja laula _Let It Go_ parhaalla oopperaäänelläsi!",
    "Anna jonkun kaverisi meikata sinut hullun näköiseksi.",
    "Tee haarahyppyjä, 2 minuuttia.",
    "Pyörähdä ympäri kymmenen kertaa ja yritä sen jälkeen kävellä suoraan.",
    "Mene koputtamaan jonkun oveen ja kysy jotain, esim. Missä on vessa?",
    "Juokse talosi ympäri 3 kertaa"
]
